[package]
name = "rg-server-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rg-common = { path = "../rg-common" }

serde.workspace = true
serde_json.workspace = true
