[package]
name = "socks5_protocol"
version = "0.1.0"
edition.workspace = true

[dependencies]
bytes.workspace = true
tokio = {workspace = true }
error.workspace = true
percent-encoding.workspace = true
serde = { version = "1.0.217", features = ["derive"] }