[package]
name = "error"
version = "0.1.0"
edition.workspace = true

[dependencies]
thiserror.workspace = true
tokio.workspace = true
http.workspace = true
base64.workspace = true
anyhow.workspace = true
trust-dns-resolver.workspace = true